### PR TITLE
Scarlandian programmer #31 character create view

### PR DESCRIPTION
**Pull request by ScarlandianProgrammer**
Added the character create page, and made some test data to make sure that the functionality works.

### CODE REVIEW

**Review by NullPointer1331 — COMMENTED** [review]
It will need more work in the future, but I think it's in a state where it could be pulled to main, but before that I'd like to know why you added test data when we already have data (also if it was necessary, it would make more sense in the Data folder rather than its own).

**Comment by ScarlandianProgrammer** [comment]
Honestly, I didn't know that we already had the data in the database. I thought that if we had it, the update-database command would add it in a new migration. I just did that to make sure the functionality worked. I'm not sure how to insert the JSON into the database, so If either you or John could show me/ send me some docs that I could look at, then I should be good. That was my bad.

**Comment by NullPointer1331** [comment]
We don't currently have the data automatically inserted, instead you open the site, click Data then Import Data

**Review by NullPointer1331 — APPROVED** [review]
Feel free to merge this once you've read the previous comment

**Pull request merged**
