### PR TITLE
ScarlandianProgrammer #36 DB helper methods

### PR DESCRIPTION
**Pull request by ScarlandianProgrammer**
I added the IDBHelper and DBHelper models, and started implementing them into the Create.cshtml view. I've made all of the Get and GetAll methods that I think we need for now.

### CODE REVIEW

**Review by NullPointer1331 — CHANGES_REQUESTED** [review]
There's a few things that need changing, first, in the description for your pull requests you should include Closing #(Insert issue number here). Next, it would make more sense to check if the userid is null in the get version of Create rather than the post. Most importantly, the reason we need a dbcontext in the first place is so pieces of code like 
`Race race = await _context.Races
                        .Where(r => r.RaceId == character.RaceId)
                        .Include(r => r.Proficiencies)
                        .ThenInclude(rp => rp.Proficiency)
                        .Include(r => r.Features)`
can be simplified, so those dbhelper methods need to get all of the component objects of the things they're getting. Before you implement that, you should first update this branch to match main, since there have been changes that could change some of what you need to write.

**Comment by NullPointer1331** [comment]
Oh, and 2 more things to note, this pull is pretty close to meeting the requirements for #63 so with a few changes, it could close that as well. And to update the branch to main, you can make a pull request, pulling from main and pushing to the branch, the opposite of what we usually do.

**Comment by ScarlandianProgrammer** [comment]
Okay, I'll try to get that done by tomorrow.

**Comment by ScarlandianProgrammer** [comment]
I think I implemented it the way it should be, at least to the best of my knowledge.

**Comment by ScarlandianProgrammer** [comment]
I added some basic implementation to the Create.cshtml view. Since I don't know how the populateEffect() method works in the CharacterController, I haven't removed it yet. If you could double-check that the objects are being constructed correctly in the Get and GetAll methods, that'd be great.

**Review by NullPointer1331 — APPROVED** [review]

**Pull request merged**
